<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Kakehashi.UI.Contracts</RootNamespace>
    <AssemblyName>Kakehashi.UI.Contracts</AssemblyName>
    <UseWinUI>true</UseWinUI>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <Platforms>x64;ARM64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kakehashi.SharedKernel\Kakehashi.SharedKernel.csproj" />
  </ItemGroup>

</Project>
