<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>__ROOT_NAMESPACE__.Modules.Notes.Application</RootNamespace>
    <AssemblyName>__APP_NAME__.Modules.Notes.Application</AssemblyName>
    <Platforms>x64;ARM64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\__APP_NAME__.SharedKernel\__APP_NAME__.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\Shared\__APP_NAME__.Application.Abstractions\__APP_NAME__.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Shared\__APP_NAME__.Mediator\__APP_NAME__.Mediator.csproj" />
    <ProjectReference Include="..\__APP_NAME__.Modules.Notes.Domain\__APP_NAME__.Modules.Notes.Domain.csproj" />
  </ItemGroup>

</Project>
